# Generated by Django 5.1.1 on 2024-11-15 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('shop', '0002_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('order_id', models.IntegerField(max_length=50)),
                ('rayzorpay_payment_id', models.CharField(blank=True, max_length=50)),
                ('payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_items', models.IntegerField()),
                ('adrress', models.TextField()),
                ('phone', models.BigIntegerField()),
                ('pin', models.IntegerField()),
                ('order_id', models.IntegerField(max_length=50)),
                ('payment_status', models.CharField(default='Pending', max_length=50)),
                ('delivery_status', models.CharField(default='pending', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
