# Generated by Django 5.1.1 on 2024-11-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_details_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_table',
            name='order_id',
            field=models.CharField(max_length=50),
        ),
    ]
